### ISSUE TITLE
choose voicechat or session mode

### ISSUE THREAD

**Issue by MagnusDrumsTrumpet** [elieserdejesus/JamTaba#139] opened 2015-11-15 17:16 UTC
like in Rea also two other modes are possible,
 actually voicchat is not so bad to explain smth by talking or give an example promt more
session mode i never understood hehe but maybe important
 but as it is right now first choice should always be the normal ninjam mode in regarsd of every beginner also 

greets from the fantastic Maggy

**Comment by Ezeer** [comment] 2015-11-16 09:13
**like in Rea also two other modes are possible,**
In ReaNinjam ? Where ? Perhaps you are talking about WahJam , i remember having seen that kind
of feature somewhere .

Anyway , a kind of Jamtaba lounge could be nice yes , without connection with the ninjam servers .
A Voice chat for Jamtaba users ... there is also a video chat planned .
Jambata should use a direct mode ( also ) in the future ( not using intervalic ) , so may be it's time to start to think at non-ninjam specific features ...

**Comment by MagnusDrumsTrumpet** [comment] 2015-11-16 09:41
hey Ezee)all i compare as reaninjam is just the vst plugin from ninjam in reaper same as ninjam standaloneas manyothers and me are used to that playing a longtime we use those basic possibilitys of that so i think it is impotrant to have all those groundfunctions from that in jamtaba as basic thera re many already in jamtaba right now and the best therare super features in jamtabe i love that will possibly be never in ninjam cause i think ninjam will not be developped anymore so i am very glad of you guys to developp this wonderful jamtaba project) so the the modes to switch are under the local channels in ninjam to switchin my opinion voicechat is good to have for talking promt to people in the room while they are an whole bpi away they can hear you promt saying something actually if you play again the you have to switch to normal ninjam back to kill the latency in fitting to the bpi moving back
complecated thing that ninjam system to many ppl they dont understand exactly and so dont use it or are afraid to play or play some shit 
))))

ok have to wor abit sadly this here is so much more interessing  hmmmmmmm
Thy youre great)
btw if you see the plugin windo from ninjam as vst  you will see and know alot what i mean )

 


     Ezee <notifications@github.com> schrieb am 10:13 Montag, 16.November 2015:
   

 like in Rea also two other modes are possible,
In ReaNinjam ? Where ? Perhaps you are talking about WahJam , i remember having seen that kind
of feature somewhere .Anyway , a kind of Jamtaba lounge could be nice yes , without connection with the ninjam servers .
A Voice chat for Jamtaba users ... there is also a video chat planned .
Jambata should use a direct mode ( also ) in the future ( not using intervalic ) , so may be it's time to start to think at non-ninjam specific features ...—

**Comment by Ezeer** [comment] 2015-11-16 09:58
**i think it is impotrant to have all those groundfunctions from that in jamtaba as basic **
i agree with that .

thanks , i've found the chat voice options : 
![capture-1](https://cloud.githubusercontent.com/assets/1283808/11179025/da2b1e04-8c50-11e5-9412-9d79bfd309f6.jpg)

and also the **warning**....
![capture-2](https://cloud.githubusercontent.com/assets/1283808/11179034/ea450cf0-8c50-11e5-833b-f5a1afec5e3c.jpg)

**Comment by elieserdejesus** [comment] 2015-11-16 16:24
I think the voice chat is a goot thing, but a little complex from a programming point of view. We need think in many things before start this.

In my opinion the session mode is something useless in ninjam. Nobody use this, so I think we can't work in a feature if nobody is using, and this feature is very complex, very time consuming. The replacement for ninjam session mode is Ohm Studio.

**Comment by MagnusDrumsTrumpet** [comment] 2015-11-16 18:59
yeah no sessionmode needed)))
 we often use voicechat for explanations promt
but here also ... default  normal ninjam !!!
 no confusing the ninjamers especially the new ones )
so maybe hide the voicechat abit  uhuhu )

**Comment by Ezeer** [comment] 2015-11-16 19:24
**uhuhu )**
ohoho ... nice one ! ah ah ah ....uhuhuh ...^^

**Comment by jonjamcam** [comment] 2015-11-16 21:19
I think a voice chat outside the ninjam stream is a better approach, like a direct jamtaba-to-jamtaba stream with a very low bandwidth consumption. IMHO A voice chat should not be part of the music being played (nor should be recorded), but rather like the text chat.....it functions as an external source of commenting and information...

It makes no sense to me sending realtime audio during intervallic jams.

**Comment by Ezeer** [comment] 2015-11-16 21:46
**It makes no sense to me sending realtime audio during intervallic jams.**
yes , a separated stream "sounds" better to me .

Starting point  : ( with code free to use ) 
Voice Chat Using Client/Server Architecture : http://www.codeguru.com/cpp/i-n/ieprogram/voice/article.php/c4371/Voice-Chat-Using-ClientServer-Architecture.htm

>Environment: Visual C++ 6.0, Windows 98/XP
Application Details
This software is based on the client/server architecture. Communication between the clients is established through the server. Initially, the server is started. Clients connect to the server host. The server sends the new client list to all the existing clients. The client can select a destination user from the user combo box. The software also provides save and play (the user can save the sound and play it later). The client also has a volume control feature. When the client application is started, a microphone select option (recording) is enabled and the microphone mute option (playing) is checked automatically by the program. (The user doesn't have to worry about the external settings.)
.

**Comment by elieserdejesus** [comment] 2015-11-16 23:05
Ok Ezee.

**Comment by Ezeer** [comment] 2015-11-16 23:32
The server part ... will run in GAE .
So we must use something that can run on it . ( that is a problem for me )
And i'm not aware about that elieser ...

Or we forget the client/server architecture and go for peer to peer , perhaps using the server to
resolve users ip ?

**Comment by elieserdejesus** [comment] 2015-11-17 00:48
Ezee, I think the best option is p2p:
1. At moment we are restricted by GAE options. We can't create a tcp socket listening in some custom port in GAE, so client/server using TCP/IP is not possible.
2. The real time jams are p2p. The difference between a real time room and a voice chat room is just the size of jitter buffer. In a voice chat we want some buffer to avoid gaps in audio. It's ok use a buffer up to 250 ms, this will add latency but this is acceptable to "human" conversation. In real time jams teh buffer size is very small to avoid latency, something like 10-15 ms. So, if we work in voice chat using p2p we are working in the real time rooms too, it's the same thing, same architecture, same codecs, etc.

**Comment by Ezeer** [comment] 2015-11-17 00:53
Good !

**Comment by pljones** [comment] 2016-08-07 10:10
Hi, duplicate of https://github.com/elieserdejesus/JamTaba/issues/5

**Comment by jonjamcam** [comment] 2018-03-10 03:16
Hey @elieserdejesus and @pljones . Just noticed reaninjam's code was made public recently, so I was thinking if voice chat is something easier to achieve now and if it is a feature still being considered for jamtaba. Talking over ninjam is very common and it's a bit complicated with the long delay.

**Comment by pljones** [comment] 2018-03-10 08:20
If it's done:
- Allow it in the same connection as an intervallic jam
- But require it on a separate channel
- Filter the channel for voice use, making it more (data) compressible
- Use low quality, high data compression on it

That's to discourage people from using it for anything but poor latency voice whilst still letting them use the connection for jamming normally.

**Comment by jonjamcam** [comment] 2018-03-10 09:59
> That's to discourage people from using it for anything but poor latency voice whilst still letting them use the connection for jamming normally.

Or it could be activated only by pressing space bar for example like a talkback. When released, normal mode resumes.

Just some ideas too😀

**Comment by MagnusDrumsTrumpet** [comment] 2018-03-10 11:10
Or it could be activated only by pressing space bar for example like a talkback. When released, normal mode resumes.Just some ideas too 😀
i would really love that) 

    jonjamcam <notifications@github.com> schrieb am 10:59 Samstag, 10.März 2018:
 

 
That's to discourage people from using it for anything but poor latency voice whilst still letting them use the connection for jamming normally.
Or it could be activated only by pressing space bar for example like a talkback. When released, normal mode resumes.Just some ideas too 😀 —

**Comment by MagnusDrumsTrumpet** [comment] 2018-03-10 11:13
also just to tell in jamming prompt for instance      please start at 1       or     groove is running       or ....
 

    jojo jo <jojo4u72@yahoo.com> schrieb am 12:10 Samstag, 10.März 2018:
 

 Or it could be activated only by pressing space bar for example like a talkback. When released, normal mode resumes.Just some ideas too 😀
i would really love that) 

    jonjamcam <notifications@github.com> schrieb am 10:59 Samstag, 10.März 2018:
 

 
That's to discourage people from using it for anything but poor latency voice whilst still letting them use the connection for jamming normally.
Or it could be activated only by pressing space bar for example like a talkback. When released, normal mode resumes.Just some ideas too 😀 —

**Comment by elieserdejesus** [comment] 2018-03-10 14:09
> Allow it in the same connection as an intervallic jam
> But require it on a separate channel
> Filter the audio signal for a voice use profile, making it more (data) compressible
> Use low quality, high data compression on it

Good ideas @pljones .  The 2nd (separated channel) is a bit complicated. Are you thinking in something like a 3rd channel used to voice chat only? I like the idea, but in public servers we are limited to 2 channels. This maxChannels limitation is a problem when xmiting video streams too.

**Comment by pljones** [comment] 2018-03-10 17:59
Simple: if people find the public jam servers aren't suitable for video chats, they'll go somewhere that's intended for video chats.

**Closed** 2020-04-06 17:44 UTC
Labels: enhancement
