### ISSUE TITLE
lot of crash   "unable writing"  and hard to connect back after

### ISSUE THREAD

**Issue by DoublebassOO** [elieserdejesus/JamTaba#878] opened 2017-06-16 18:49 UTC
hello
i have a lot disconnection with error "unable to write"  this 10 last days even much more .
either on ninjamer or ninbot server .  Not sure , but i thinks it happens some weeks after the installation of the new version of jamtaba2 2.02 , 

a lot of ninjamers seems to have more pb of disconnestion even with reaninjam.

any suggestion to know where it comes from ?

ps i  use  vst jamtaba in reaper Win10 64 bits , through a vpn tunnel  but it was ok before  using it for a long time now

thanks for your help guys

**Comment by elieserdejesus** [comment] 2017-06-17 00:21
Hi @DoublebassOO !

> i have a lot disconnection with error "unable to write" this 10 last days even much more .
either on ninjamer or ninbot server 

Both errors are related with unreacheable servers.

> a lot of ninjamers seems to have more pb of disconnestion even with reaninjam.

It seems like a problem on the server side or ISP cables in your region. It's rare, but sometimes a fiber optic cable is broken and the internet is messy, but this is a huge guess.

I played some minutes today (06/16/2017) and have 2 or 3 disconnections too (in ninbot). I was thinking the problem is my wifi, but maybe this is a more general problem in servers.

**Comment by jonjamcam** [comment] 2017-06-17 00:30
Hey @DoublebassOO  and @elieserdejesus . I've connected these last two days for more than 2 hours each with no problems whatsoever. Not full servers though. I Heard once slick was disconnected when rp crashed using wahjam.

**Comment by elieserdejesus** [comment] 2017-06-17 11:47
Hi @jonjamcam !

> EDIT: Now I remember when browsing loops or taking too much time to select a loop to load in the looper I got the "unable to write" msg and a disconnection. The weird thing is this happened when using my local server (localhost) in the same computer

This make sense. Possibly (not checked the code yet) the loop browser window is blocking Qt and all network stuff is blocked too. If the client (JamTaba) doesn't send data to server a time out error will be generated and server will disconnect the client (JamTaba).  This explain the error when browsing loops, but I think it's not related with the general disconnections.

**Comment by jonjamcam** [comment] 2017-08-04 17:16
Yesterday using jamtaba vst inside reaper I had a DAW crash and pipaxis told me he had the same crash at exactly the same moment. So there is for sure something happening in a room that's making jamtaba crash independent of OS (I use windows 7 and pipaxis has mac). No looper being used at thrus time.

What I remember of that session was:

1 reaninjam user, 1 wahjam user, two jamtaba users, 1 unknown.

Reaninjam nor wahjam were affected afaikt.

I'll do my best to try to see a pattern in the future.

**Comment by elieserdejesus** [comment] 2017-08-05 13:21
Hi @jonjamcam!  

Maybe wahjam is sending some stuff JamTaba is not prepared to receive, something in the ninjam network protocol level. 

You know if the wahjam user is really using wahjam? Maybe was using jammr? I think jammr has some "custom" stuff in the protocol, but I don't know if is possible connect in public servers using jammr.

**Comment by jonjamcam** [comment] 2017-08-05 15:06
Now that you mention it I'm not sure if it was jammr or wahjam. Wahjam uses "channel0" as text in the instrument placeholder, so it was my conclusion, but I don't know jammr.

**Comment by jonjamcam** [comment] 2017-09-19 23:02
Documenting some recent problems for the record:

1.- I had this error today using my own compiled vst version:

![image](https://user-images.githubusercontent.com/15310433/30619236-d087a4ee-9d74-11e7-9159-a4448234287c.png)

In my system (pretty old BTW) the use of the looper sometimes bottlenecks the connection (as it happened in 20.0.20 using my own private server too).

2.- I got a crash in standalone (also compiled locally) while testing the video feature yesterday

**Comment by elieserdejesus** [comment] 2017-09-19 23:54
Jon, some clue in the **log.txt**?

**Comment by jonjamcam** [comment] 2017-09-20 00:43
Unfortunately no clues there. I'm looking for a pattern. BTW videojamming is more than fantastic!

**Comment by elieserdejesus** [comment] 2017-09-20 00:52
@jonjamcam  this picture put a big smile in my face. Very cool! It's a pleasure see the video is working.

Can you take another screenshot (maybe with more cams) to put in JTABA website? This picture is very cool, but it's cropped in the right side.

**Comment by jonjamcam** [comment] 2017-09-20 00:55
pic updated! was just a quick cut

**Comment by elieserdejesus** [comment] 2017-09-20 12:15
> pic updated! was just a quick cut. I'll try to get a full room with cams though

thanks @jonjamcam !

**Comment by elieserdejesus** [comment] 2018-07-28 23:08
Closing the issue, I suppose is not a problem in last version.

**Closed by elieserdejesus** 2018-07-28 23:08 UTC
