### ISSUE TITLE
VST racks for the other musicians in a server

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#108] opened 2015-11-08 17:13 UTC
This idea came to my mind while writing the user's guide. Just to add some compression and eq  Maybe it's too early for this, but would be so cool in the future!

**Comment by elieserdejesus** [comment] 2015-11-08 20:13
Jon, this idea is in my mind too, and actually the audio code is prepared for this.

Every time I'm jamming I miss a high pass filter (low cut) in ninjam tracks, because many musicians play with a lot of low freqs, and this not sounds good in a 4-6 musicians jam. In general the bass notes are masked because we have a lot of low freqs in guitars and keyboards in the room. 
My idea is put a simple check box to activate deactivate a high pass filter using a pre defined frequency (180 Hz).  This is a simple thing in GUI, and its not too complicated in programming, but the audio mix quality can be very improved. Jamming in a clear mix is a very nice experience. 

This is the first step, the next step is allow VSTs in the tracks.

And the last step is release some native plugins, like Logic and Reaper.

**Comment by Ezeer** [comment] 2015-11-08 20:17
That sounds clever !
:+1:

**Comment by jonjamcam** [comment] 2015-11-08 20:46
Yes. That's enough to jam comfortably, but the frequency is critical. At least can we have a small knob to select from 80-400 if it's not too complicated.

**Comment by pljones** [comment] 2016-08-07 10:07
Possible duplicate of multi-out for the VST version:
https://github.com/elieserdejesus/JamTaba/issues/1
(seeing as that would allow each channel to have its own effects added)

For the standalone, once the internal "multi-out" architecture is there, this could be added.

**Comment by elieserdejesus** [comment] 2017-09-21 00:57
moved to wishlist https://github.com/elieserdejesus/JamTaba/issues/907

**Closed by elieserdejesus** 2017-09-21 00:57 UTC
Labels: enhancement, wishlist
