### ISSUE TITLE
Suggestion for improving VST hosting

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#604] opened 2016-09-17 06:33 UTC
@elieserdejesus Reading the VST plugin host part of Jamtaba Standalone I found that you used VSTBoard approach. As we know some plugins are not working OK (crash, no sound, no midi input, etc.), so I tested VSTBoard and noticed some of my plugins do not work there too, but they work in some other VST hosts I've tested.

 I found this other software called VSTHOST that has some code opensource and my plugs do work there. I don't know enough to be able to read the code myself, but if there's of some use to improve Jamtaba VST hosting, maybe you could give it a look if you have time.

http://www.hermannseib.com/english/vsthost.htm

here's the code the author released opensource (windows only I think):

http://www.hermannseib.com/programs/vsthostsrc.zip

I read the license http://www.gnu.org/copyleft/lesser.html and I think the code is usable, but not modifiable if I'm not mistaken.

**Comment by elieserdejesus** [comment] 2016-09-17 11:40
@jonjamcam , I know Vst Host, this is the most famous open source VST Host. Herman Seib (the author) is a great guy and contributed a lot sharing your knowledge in VSt Host project and in kvraudio forum (he is using the nick name *Arakula's*).  If I rememver correctly VST Board is based (but not copyed) in Vst Host too.

Can you test your **not working in Jamtaba** plugins in VST Host?

**Comment by jonjamcam** [comment] 2016-09-17 13:22
> Can you test your not working in Jamtaba plugins in VST Host?

Sure. I use a lot **Hypersonic 1** in win7. It's very old, but my favorite still for years.

It works fine in reaper and VST host. I did a quick test in **Forte** too successfully. In Jamtaba it loads correctly, but most instruments do not emit any sound at all (very few do).

Others I could test are the ones that have problems posted here https://github.com/elieserdejesus/JamTaba/issues/91 and here https://github.com/elieserdejesus/JamTaba/issues/23, but some do not work at all in win7, so I'd have to install them in XP.

I'll post the results here.

**Comment by jonjamcam** [comment] 2017-02-08 22:42
@elieserdejesus I gave it another thought and maybe it's not a good idea to do this change. I fear you'll spend too much time on this one and then the testing phase I can only test in windows. Any problems in Mac or Linux could be a mess. I rather focus testing time in stability.

To use Hypersonic 1 I load it in reaper and it works just fine. So Closing....

**Comment by elieserdejesus** [comment] 2017-02-09 09:47
@jonjamcam , maybe the issue is not too complex to solve. For example, maybe Hypersonic is using some different channel scheme and JamTaba is not creating these channels correctly.  Another possibility: Hypersonic is VST 2.3 or 2.2, not 2.4 and is using something different than expected.

If this is the case solving for Hypersonic will solve for another plugins too, so I think worth keep the issue opened for while.

**Comment by elieserdejesus** [comment] 2017-02-09 09:49
@jonjamcam , how big is Hypersonic 1 dll? Can you send me (email or post here)?

**Comment by jonjamcam** [comment] 2017-02-09 14:52
> how big is Hypersonic 1 dll?

not much the dll itself, but the sound library is 150 mb

[hyp.txt](https://github.com/elieserdejesus/JamTaba/files/763997/hyp.txt)

**Comment by elieserdejesus** [comment] 2017-02-09 15:11
Is possible test the mentioned issues without the library?

**Comment by jonjamcam** [comment] 2017-02-09 15:21
> Is possible test the mentioned issues without the library?

I don't thnk so. Hypersonic is more like a sampler than synth. It will ask you for the lib path at launch.

**Comment by elieserdejesus** [comment] 2017-10-12 21:38
@jonjamcam , I will close this issue. I have an idea (for long term future) to rewrite JamTaba using [JUCE](https://www.juce.com/). Juce is the best tool for audio applications. You get Standalone, VST 2, VST 3, AU, AAX, LADSPA , etc. all for free. Many plugins and hosts we are using are coded using juce.

**Closed by elieserdejesus** 2017-10-12 21:38 UTC
