### ISSUE TITLE
High memory use when cam is turned on when DROIDCAM driver is used

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#951] opened 2017-10-23 14:23 UTC
memory use gets higher and higher when cam is used and connected to a server. My tests show droidcam specifically has this problem.

I got a crash because of this after some minutes:

default.DEBUG     [10:44:18:744] Exporting  "Black_nm" => "BaseTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Black_nm" [, line 0]
default.DEBUG     [10:44:18:749] Exporting  "Black_nm" => "Chat.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Black_nm" [, line 0]
default.DEBUG     [10:44:18:754] Exporting  "Black_nm" => "Chords.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Black_nm" [, line 0]
default.DEBUG     [10:44:18:760] Exporting  "Black_nm" => "Dialogs.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Black_nm" [, line 0]
default.DEBUG     [10:44:18:767] Exporting  "Black_nm" => "General.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Black_nm" [, line 0]
default.DEBUG     [10:44:18:771] Exporting  "Black_nm" => "LocalTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Black_nm" [, line 0]
default.DEBUG     [10:44:18:777] Exporting  "Black_nm" => "MainWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Black_nm" [, line 0]
default.DEBUG     [10:44:18:781] Exporting  "Black_nm" => "NinjamWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Black_nm" [, line 0]
default.DEBUG     [10:44:18:786] Exporting  "Black_nm" => "PublicRooms.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Black_nm" [, line 0]
default.DEBUG     [10:44:18:819] Exporting  "Flat" => "BaseTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Flat" [, line 0]
default.DEBUG     [10:44:18:823] Exporting  "Flat" => "Chat.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Flat" [, line 0]
default.DEBUG     [10:44:18:827] Exporting  "Flat" => "Chords.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Flat" [, line 0]
default.DEBUG     [10:44:18:831] Exporting  "Flat" => "Dialogs.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Flat" [, line 0]
default.DEBUG     [10:44:18:835] Exporting  "Flat" => "General.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Flat" [, line 0]
default.DEBUG     [10:44:18:839] Exporting  "Flat" => "LocalTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Flat" [, line 0]
default.DEBUG     [10:44:18:842] Exporting  "Flat" => "MainWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Flat" [, line 0]
default.DEBUG     [10:44:18:847] Exporting  "Flat" => "NinjamWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Flat" [, line 0]
default.DEBUG     [10:44:18:852] Exporting  "Flat" => "PublicRooms.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Flat" [, line 0]
default.DEBUG     [10:44:18:857] Exporting  "Ice" => "BaseTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Ice" [, line 0]
default.DEBUG     [10:44:18:862] Exporting  "Ice" => "Chat.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Ice" [, line 0]
default.DEBUG     [10:44:18:865] Exporting  "Ice" => "Chords.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Ice" [, line 0]
default.DEBUG     [10:44:18:872] Exporting  "Ice" => "Dialogs.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Ice" [, line 0]
default.DEBUG     [10:44:18:877] Exporting  "Ice" => "General.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Ice" [, line 0]
default.DEBUG     [10:44:18:882] Exporting  "Ice" => "LocalTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Ice" [, line 0]
default.DEBUG     [10:44:18:886] Exporting  "Ice" => "MainWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Ice" [, line 0]
default.DEBUG     [10:44:18:891] Exporting  "Ice" => "NinjamWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Ice" [, line 0]
default.DEBUG     [10:44:18:896] Exporting  "Ice" => "PublicRooms.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Ice" [, line 0]
default.DEBUG     [10:44:18:899] Exporting  "Navy_nm" => "BaseTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Navy_nm" [, line 0]
default.DEBUG     [10:44:18:903] Exporting  "Navy_nm" => "Chat.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Navy_nm" [, line 0]
default.DEBUG     [10:44:18:907] Exporting  "Navy_nm" => "Chords.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Navy_nm" [, line 0]
default.DEBUG     [10:44:18:911] Exporting  "Navy_nm" => "Dialogs.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Navy_nm" [, line 0]
default.DEBUG     [10:44:18:914] Exporting  "Navy_nm" => "General.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Navy_nm" [, line 0]
default.DEBUG     [10:44:18:918] Exporting  "Navy_nm" => "LocalTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Navy_nm" [, line 0]
default.DEBUG     [10:44:18:923] Exporting  "Navy_nm" => "MainWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Navy_nm" [, line 0]
default.DEBUG     [10:44:18:927] Exporting  "Navy_nm" => "NinjamWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Navy_nm" [, line 0]
default.DEBUG     [10:44:18:931] Exporting  "Navy_nm" => "PublicRooms.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Navy_nm" [, line 0]
default.DEBUG     [10:44:18:951] Exporting  "Rounded" => "BaseTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Rounded" [, line 0]
default.DEBUG     [10:44:18:955] Exporting  "Rounded" => "Chat.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Rounded" [, line 0]
default.DEBUG     [10:44:18:960] Exporting  "Rounded" => "Chords.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Rounded" [, line 0]
default.DEBUG     [10:44:18:964] Exporting  "Rounded" => "Dialogs.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Rounded" [, line 0]
default.DEBUG     [10:44:18:969] Exporting  "Rounded" => "General.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Rounded" [, line 0]
default.DEBUG     [10:44:18:973] Exporting  "Rounded" => "LocalTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Rounded" [, line 0]
default.DEBUG     [10:44:18:978] Exporting  "Rounded" => "MainWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Rounded" [, line 0]
default.DEBUG     [10:44:18:983] Exporting  "Rounded" => "NinjamWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Rounded" [, line 0]
default.DEBUG     [10:44:18:987] Exporting  "Rounded" => "PublicRooms.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Rounded" [, line 0]
default.DEBUG     [10:44:19:005] Exporting  "Volcano_nm" => "BaseTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Volcano_nm" [, line 0]
default.DEBUG     [10:44:19:011] Exporting  "Volcano_nm" => "Chat.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Volcano_nm" [, line 0]
default.DEBUG     [10:44:19:015] Exporting  "Volcano_nm" => "Chords.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Volcano_nm" [, line 0]
default.DEBUG     [10:44:19:020] Exporting  "Volcano_nm" => "Dialogs.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Volcano_nm" [, line 0]
default.DEBUG     [10:44:19:026] Exporting  "Volcano_nm" => "General.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Volcano_nm" [, line 0]
default.DEBUG     [10:44:19:031] Exporting  "Volcano_nm" => "LocalTrack.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Volcano_nm" [, line 0]
default.DEBUG     [10:44:19:035] Exporting  "Volcano_nm" => "MainWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Volcano_nm" [, line 0]
default.DEBUG     [10:44:19:041] Exporting  "Volcano_nm" => "NinjamWindow.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Volcano_nm" [, line 0]
default.DEBUG     [10:44:19:046] Exporting  "Volcano_nm" => "PublicRooms.css"  to  "C:/Users/jon/AppData/Roaming/JamTaba 2/Themes/Volcano_nm" [, line 0]
default.INFO      [10:44:19:047] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/JamTaba 2" [, line 0]
default.INFO      [10:44:19:355] "Starting Jamtaba 2.1.2 Standalone (x86_64) running on Windows 7 (x86_64)" [, line 0]
default.CRITICAL  [10:44:19:496] Scanner executable not founded in "C:/Users/jon/Documents/_Jamtaba github/My_Fork/JamTaba/PROJECTS/build-Standalone-static_x64-Release/release/VstScanner.exe" [, line 0]
default.DEBUG     [10:46:40:812] Setting video resolution to QSize(640, 480) [, line 0]
default.DEBUG     [10:46:45:827] Setting video resolution to QSize(160, 120) [, line 0]
default.DEBUG     [10:52:26:084] Setting video resolution to QSize(160, 120) [, line 0]
default.DEBUG     [10:56:55:992] Setting video resolution to QSize(640, 480) [, line 0]
default.WARNING   [11:01:24:822] QImage: out of memory, returning null image [, line 0]
default.WARNING   [11:01:24:920] QImage: out of memory, returning null image [, line 0]
default.WARNING   [11:01:25:329] QImage: out of memory, returning null image [, line 0]
default.CRITICAL  [11:01:31:114] 000000013FE11CFD ((module-name not available)): (filename not available): (function-name not available)
 [, line 0]
default.CRITICAL  [11:01:47:462] Exception in MainController::process [, line 0]
default.CRITICAL  [11:01:47:608] 000000013FE11CFD ((module-name not available)): (filename not available): (function-name not available)
 [, line 0]
default.FATAL     [11:01:47:609] Aborting in  MainController::process! [, line 0]
default.CRITICAL  [11:01:47:609] Configurator::signalHandler signal: 22 [, line 0]

EDIT: internal cam in my system also increases the use of memory, but the effect is slower. It shows up after some minutes.

**Comment by elieserdejesus** [comment] 2017-10-23 15:41
@jonjamcam , I see the problem in your log
> QImage: out of memory, 

100% shure is about memory.  Only droidcam has the problem? How your other cam is behaving?

**Comment by jonjamcam** [comment] 2017-10-23 15:44
>  Only droidcam has the problem? How your other cam is behaving?

Droidcam drains memory very fast, but my internal cam consumes memory too, but very slow.

**Comment by elieserdejesus** [comment] 2017-10-23 18:02
@jonjamcam , I confirmed the memory issue here.  The problem is fixed in master and working ok here, no more memory problems. Can you test with droidcam, please?

**Closed** 2017-10-23 18:01 UTC
