### ISSUE TITLE
Jamtaba2 VST does not accept shortcut keys or special keys.

### ISSUE THREAD

**Issue by NakajimaYusuke** [elieserdejesus/JamTaba#472] opened 2016-06-24 03:21 UTC
Hi, I noticed that Jamtaba2VST does not receive any shortcut keys such as "Ctrl + V" or "Ctrl + C" or etc.
These operations from the mouse are working properly. Operations from the keyboard is not working.

In addition, I found simillar problem in Jamtaba2VST. Excuse me, this is also a Japanese-related issues...
Japanese keyboard has a special key named "2byte/1byte Key" or "full-width/half-width Key"
Japanese people uses this key to switch input character between English and Japanese.
Jamtaba2VST does not accept this key too. (How about this behavior in other 2-byte character languages?)

So, in the current situation, in order to input Japanese character to Jamtaba2 VST, 
I need to type Japanese character to another input field (outside of Jamtaba2VST) and copy and paste it to Jamtaba2VST input field with the mouse operation.
This procedure is a little troublesome. I hope to improve.

If these two issues are linked,I expect that "when the shortcut issue is solved, the special key issue is also solved naturally."

**Comment by elieserdejesus** [comment] 2016-06-24 14:53
Hi @NakajimaYusuke , I think the 2 things are different. The first (Control+C and Control + V) is not complicated. 
I'm not shure how test the second issue because I don't have a japanese keyboard. It is possible change a common keyboard to simulate the "2byte/1byte" key?

**Comment by jonjamcam** [comment] 2016-06-24 17:30
@NakajimaYusuke Can you tell us please where is the "2byte/1byte" key in the keyboard below (if any)?

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Standard_Taiwanese_Keyboard_Layout.svg/420px-Standard_Taiwanese_Keyboard_Layout.svg.png)

**Comment by NakajimaYusuke** [comment] 2016-06-25 08:57
@elieserdejesus
Common keyboard might be able to simulate it in this key combination.

Alt + `
or
Alt + ~

If the second issue is quite complicated, please give priority to solving the first issue.

And, there is another report for you.
I confirmed that old version of JamtabaVST doesn't have these issues.
JamtabaVST v243 accepts both shortcut keys and special keys without any problem.


@jonjamcam
The top left corner key of second image is it. [半角/全角]
It is called "hankaku/zenkaku key" in japanese.

**Comment by elieserdejesus** [comment] 2016-06-25 12:33
Thanks for the infos @NakajimaYusuke .

> I confirmed that old version of JamtabaVST doesn't have these issues. JamtabaVST v243 accepts both shortcut keys and special keys without any problem.

The old version was writed in a different programming language (JAVA), the current version is a totally different code/technology. Is not possible "copy/paste" or adapt the old code in this case.

**Comment by elieserdejesus** [comment] 2016-07-10 15:23
Hi @NakajimaYusuke , I fixed the "Copy/paste" problem in VST plugin. Please, can you check if the other problem (hankaku/zenkaku key) is working too?

[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/356080/JamtabaVST2.zip)

**Comment by jonjamcam** [comment] 2016-07-11 00:39
@elieserdejesus  I find the **ALT GR** key is not working either. In my Spanish keyboard it makes ~, ^,`,,\,¬ characters available.

**Comment by elieserdejesus** [comment] 2016-07-11 13:56
@jonjamcam  and @NakajimaYusuke , I fixed the AltGr (Right alt key) too. Can you test in your keyboards, please?
 
[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/357217/JamtabaVST2.zip)

**Comment by NakajimaYusuke** [comment] 2016-07-11 14:09
Thanks for the fix.
I confirmed that Ctrl + Z,X,C,V,A are working properly!

But, hankaku/zenkaku key is still unresponsive.
Perhaps, my expectation was wrong...  As you said, this may be a different problem.

**Comment by elieserdejesus** [comment] 2016-07-11 17:11
@NakajimaYusuke , I`m trying understand the **hankaku/zenkaku key** issue.

I changed my windows 10 to japanese and now I can type (but not read :smile) in Japanese.

You said
> Common keyboard might be able to simulate it in this key combination.
Alt + `
or
Alt + ~

I tried these key combinations but no results here. In my windows taskbar I see some options for japanese input methods:
![image](https://cloud.githubusercontent.com/assets/1012741/16739470/aa449752-4770-11e6-9a92-55f209e19b94.png)

Based in this image I'm suposing the **hankaku/zenkaku key** is a "global" toggle key used to switch between english/alfabetic and japanese symbols. This is right? When you press the **hankaku/zenkaku key** your input method in windows taskbar is changed?

**Comment by jonjamcam** [comment] 2016-07-11 20:42
> I fixed the AltGr (Right alt key) too.

@elieserdejesus working OK here. I found some other keys not working too like CAPS LOCK, for example and some other combinations of the **shift key** like **shift-right arrow** and **shift - left arrow** (I use these to select all text for example)

**Comment by elieserdejesus** [comment] 2016-07-13 01:30
@jonjamcam and @NakajimaYusuke , I found a way to test the hankaku/zenkaku key in my keyboard. I need switch to japanese and press ALT + "top left key in my keyboard". 

I fixed (I hope) the hankaku/zenkaku key, the caps lock and SHIFT + ARROWs issues. Can you test the new version please?

[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/360539/JamtabaVST2.zip)

**Comment by jonjamcam** [comment] 2016-07-13 01:46
> the caps lock and SHIFT + ARROWs issues

@elieserdejesus yes, it's fixed now.

**Comment by NakajimaYusuke** [comment] 2016-07-13 06:48
@elieserdejesus
I tried the latest version. But my hankaku / zenkaku key still did not work.


>Based in this image I'm suposing the hankaku/zenkaku key is a "global" toggle key used to switch between english/alfabetic and japanese symbols. This is right? When you press the hankaku/zenkaku key your input method in windows taskbar is changed?

Yes. Perfectly correct. It's like a toggle switch.
![jptoggle1](https://cloud.githubusercontent.com/assets/15982547/16794121/c60e4072-4910-11e6-91b7-25e016207925.gif)
This GIF is Japanese input to Jamtaba 2 (stand alone). This is the proper behavior.
When I press the hankaku / zenkaku key, input method switches to "A"(English) or "あ"(Japanese) alternately.
But, in the current VST version, this switching doesn't work now.

**Comment by elieserdejesus** [comment] 2016-07-13 10:55
@NakajimaYusuke , In my system I got the correct behavior, but my keyboard is not a japanese keyboard. I need to know the key code of hankaku/zenkaku switch (unfortunally the microsoft documentation is not enough). 

In this [link](http://www.delphiforfun.org/Programs/Utilities/KeyCodes.htm) you can download a small program to inspect the key codes of your keyboard. Please, can you help me running this program? 

The steps are:
1 - Run the program
2 - Press the hankaku/zenkaku key (just one time)
3 - Copy the text generated in the programming here. This text will show the key code for the hankaku/zenkaku switch.

**Comment by NakajimaYusuke** [comment] 2016-07-13 11:33
Thank you. Two results were generated.

1.Switching from English to Japanese
```
OnKeyup,` Key code=243, Control keys=, Key name ........OEM specific
OnKeyDown, Key code=229, Control keys=, Key name Unassigned

```
2.Switching from Japanese to English
```
OnKeyup, Key code=244, Control keys=, Key name ........OEM specific
OnKeyDown, Key code=229, Control keys=, Key name Unassigned

```

**Comment by elieserdejesus** [comment] 2016-07-13 12:39
Thanks @NakajimaYusuke , your key codes are very different from my keyboard key codes. I added the key codes reported by you in Jamtaba. Can you test again, please?
[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/361466/JamtabaVST2.zip)

**Comment by NakajimaYusuke** [comment] 2016-07-13 13:30
I'm sorry. It was also failure. But I noticed one of the progress.
When I push the hankaku / zenkaku key, notification icon has been displayed next to the preferences.
The previous version did not have this behavior.
![jptoggle2](https://cloud.githubusercontent.com/assets/15982547/16804709/1ddaca00-4948-11e6-9c74-b10ebcec5317.gif)

**Comment by elieserdejesus** [comment] 2016-07-13 14:54
@NakajimaYusuke , a little out of topic issue: I noticed a problem in the image you posted. The pan slider is cropped. I see the same problem in Linux and Mac, but I have no problem in my windows, and I supose @jonjamcam have no problem too. Now I'm curious :) about your environment. Are you in windows? Or is a Linux + wine?
![image](https://cloud.githubusercontent.com/assets/1012741/16807874/82c6a144-48f0-11e6-831a-0e6ffa504de3.png)

**Comment by NakajimaYusuke** [comment] 2016-07-13 16:57
This is the result. Good luck!


Hit the "a" key in English mode
```
OnKeyDown, Key code=65, Control keys=, Key name a
OnKeyPress a
OnKeyup, Key code=65, Control keys=, Key name a
```

Hit the "a" key in Japanese mode
```
OnKeyDown, Key code=229, Control keys=, Key name Unassigned
OnKeyup, Key code=65, Control keys=, Key name a
```
Hit the "a" key and "Enter" key in Japanese mode (procedure for type the "あ" letter.)("あ" is the Japanese notation of "a")
```
OnKeyDown, Key code=229, Control keys=, Key name Unassigned
OnKeyup, Key code=65, Control keys=, Key name a

OnKeyDown, Key code=229, Control keys=, Key name Unassigned
OnKeyPress ・
OnKeyPress 
OnKeyup, Key code=13, Control keys=, Key name ENTER
```

For out of topic issue.
My environment is win7 64bit. (I'm planning to upgrade to Win10 soon.)
And I have been using the classic theme. Therefore, there may be slight differences in appearance.

I also have a Linux + Wine environment as a submachine. But, all of the reports of this issue so far is in win7.

**Comment by jonjamcam** [comment] 2016-07-13 21:54
> The pan slider is cropped. I see the same problem in Linux and Mac, but I have no problem in my windows, and I supose @jonjamcam have no problem too

@elieserdejesus no problem here...win7 x64

![image](https://cloud.githubusercontent.com/assets/15310433/16821154/c72249b0-4922-11e6-80c6-b63888bd14d6.png)

**Comment by elieserdejesus** [comment] 2016-07-14 14:18
@NakajimaYusuke , can you run a new test, please?
[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/363961/JamtabaVST2.zip)

@NakajimaYusuke and @jonjamcam , can you test in another DAWs (non Reaper)? I'm not shure if the current solution will work fine in another DAWs, I'm specially worried about BACKSPACE and DELETE keys.

**Comment by NakajimaYusuke** [comment] 2016-07-14 16:09
I tried the latest version.
Good job! I succeeded Japanese input to chat form. 

But, there is one inconvenient behavior. 
In Japanese mode, Enter key doesn't respond. 
In current state, I need to switch to English mode to press Enter key.

Although it is still not perfect, there was a big progress. Thank you.

I tried Jamtaba2 on Sonar X1 Studio.
As long as I was confirmed, the behavior was the same as on the reaper.
BACKSPACE and DELETE keys are working fine.

**Comment by elieserdejesus** [comment] 2016-07-14 16:41
@NakajimaYusuke , can you post the ENTER key code in english and japanese input modes? 

Another question: the ENTER is not working to send chat messages?

**Comment by NakajimaYusuke** [comment] 2016-07-14 18:56
The key code is this. Both modes were exactly the same code.
```
OnKeyDown, Key code=13, Control keys=, Key name ENTER
OnKeyPress 

OnKeyup, Key code=13, Control keys=, Key name ENTER
```


>the ENTER is not working to send chat messages?

Enter key might be working to send chat messages even in Japanese mode.
But, It is not working to determine (confirm) Japanese words.

Japanese input method may be a little complicated. Typed letters are not input directly.
In ordinary Japanese input method, the message sending requires 5 steps.

Step1. Switch to Japanese mode (Using hankaku/zenkaku key)
Step2. Type letters 
Step3. Select the notation (Using space bar or etc...)
Step4. Determine the notation (Using Enter key)
Step5. Send messages (Using Enter key)

In this way, Enter key is used twice as different usage.
In current state, it seems step3 and step4 is not working properly.


By the way, I think that these mechanisms may be too regional and too unique.
I don't want to increase your tasks for this local issue.
From this area, cooperation of a Japanese coder may be desirable...
@teamikl,@takeshitaleo, Please advice to solve this issue, if you have a little time!

**Comment by elieserdejesus** [comment] 2016-07-14 20:10
@NakajimaYusuke 
> In current state, it seems step3 and step4 is not working properly.

I confirmed the problem in step 3 here, the spacebar is not opening the japanese notation menu.
In my keyboard the key code for space bar is different when I`m using japanese input method:
**Pressing space bar in normal (portuguese) mode:**
```
OnKeyDown, Key code=32, Control keys=, Key name SPACEBAR
OnKeyPress  
OnKeyup, Key code=32, Control keys=, Key name SPACEBAR
```
**Pressing space bar in Japanese mode:**
```
OnKeyDown, Key code=229, Control keys=, Key name Unassigned
OnKeyPress  
OnKeyup, Key code=32, Control keys=, Key name SPACEBAR
```

I will investigate this issue soon.

**Comment by elieserdejesus** [comment] 2016-07-16 19:14
Hi @NakajimaYusuke , I solved the problems we discussed before in my machine. Can you test in your keyboard, please?
[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/367458/JamtabaVST2.zip)

**Comment by NakajimaYusuke** [comment] 2016-07-20 08:47
This issue seems very tough... I tested it. But, Enter key doesn't work yet.
In this version, I could not find the difference in behavior from the previous version.

Sorry for my late reply. I've updated my PC to Win10.

**Comment by elieserdejesus** [comment] 2016-07-23 14:26
@NakajimaYusuke , now I'm using a [windows api function](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318566(v=vs.85).aspx) to detect when the IME (Input Method Editor) is opened or not. Can you test again, please?
[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/379787/JamtabaVST2.zip)

**Comment by NakajimaYusuke** [comment] 2016-07-23 16:10
Succeeded! It worked perfectly. Thank you for your many good work.
I can recommend Jamtaba2VST to all of Japanese people from now on. You're great!

**Comment by elieserdejesus** [comment] 2016-07-24 00:19
nice news @NakajimaYusuke , thanks for your help testing this issue, see you!

**Closed** 2016-07-24 00:19 UTC
