### ISSUE TITLE
Jamtaba standalone crashes if previously the vst plugin Jamtaba was used

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#101] opened 2015-11-07 19:51 UTC
I use mostly Standalone, but some times when I use reaper with Jamtaba VST (which works just fine) and then switch back to Standalone something happens that I have a crash. Deleting the Jamtaba64.json seems to correct the problem.

The problem seem to be that the blacklisted plugins feature is not blocking all the time, so what I did was I removed the plugin .dll that was generating problems from the directory and test again and NO CRASH.

**Comment by elieserdejesus** [comment] 2015-11-07 20:31
Humm, I'm thinking in a possibly cause here.
Maybe the VSt plugin is rewriting you json and deleting your black list.
Can you test this jon?
1 - Open Standalone and add some bad ass plugins in your black list.
2 - Close Standalone, open the json and check if the black list is correct.
3 - Open the VST plugin
4 - Remove the VST plugin from your DAW (this will cause the json rewrite).
5 - Check your black list in the json.

**Comment by jonjamcam** [comment] 2015-11-07 21:01
3.- "Open the VST plugin". i did in reaper
4.- "Remove the VST plugin from your DAW (this will cause the json rewrite)." Just remove from track and close reaper? Did that.

Json still has the blacklisted plugs and didn't have a crash.......mmmmm...I was wrong I guess....

**Comment by jonjamcam** [comment] 2015-11-07 21:03
Ok I got it. it has nothing to do with plugins

When I open the standalone with two channels and then the plugin.......then the crash produces......this doesn't happen with one channel only

**Comment by elieserdejesus** [comment] 2015-11-07 22:01
Jon, when you crash exactly? In plugin scanning?

**Comment by jonjamcam** [comment] 2015-11-07 22:57
At the very beggining. where the screen that says "loading rooms list" appears.

**Comment by Ezeer** [comment] 2015-11-07 23:03
Hey ! you mean you use the standalone + the plugin in same time ?
It is the same code executed twice , but as we use mutex , that could be a thread conccurency problem : 
>Concurrency and data structures
Threads in the same process share the same address space. This allows concurrently running code to couple tightly and conveniently exchange data without the overhead or complexity of an IPC. ##When shared between threads, however, even simple data structures become prone to race conditions if they require more than one CPU instruction to update##: two threads may end up attempting to update the data structure at the same time and find it unexpectedly changing underfoot. ##Bugs caused by race conditions can be very difficult to reproduce and isolate.##

**Comment by elieserdejesus** [comment] 2015-11-07 23:31
Ah, this is the problem Jon? Are you opening the standalone and VST plugin at same time?

**Comment by jonjamcam** [comment] 2015-11-07 23:33
I'm not.

1.- First I open the standalone.
2.- add channel
3.- close standalone
4.- open reaper with jamtaba vst
5.- close reaper
6.- open standalone
7.- CRASH

**Comment by Ezeer** [comment] 2015-11-07 23:36
thx jon .
i suggest : 
1.- First I open the standalone.
2.- add channel
3.- close standalone

3-a rename the log to save it from being overwrited

4.- open reaper with jamtaba vst
5.- close reaper
6.- open standalone
7.- CRASH

Now you have two logs , we can compare ...
eh eh

**Comment by Ezeer** [comment] 2015-11-07 23:40
i also feel it is due to a change in the json , related to the chanels that exists or not in standalone and vst :
 
"inputs": {
        "channels": [
            {
                "name": "your channel",
                "subchannels": [
                    {
                        "boost": 0,
                        "channelsCount": 0,
                        "firstInput": -1,
                        "gain": 1.1000000238418579,
                        "midiChannel": 0,
                        "midiDevice": -1,
                        "muted": false,
                        "pan": 0,
                        "plugins": [
                        ]
                    }
                ]
            }
        ]
    },

So please copy the Json too , for we compare .
thx

**Comment by jonjamcam** [comment] 2015-11-07 23:47
Ok. 

1.- Delete json file
2.- Run Standalone. This are the json and log

[_1_Jamtaba64 - copia.json.txt](https://github.com/elieserdejesus/JamTaba/files/29429/_1_Jamtaba64.-.copia.json.txt)
[log.txt](https://github.com/elieserdejesus/JamTaba/files/29430/log.txt)

3.- Add channel in standalone
4.- close standalone
5.- Run reaper with jamtaba vst 
4.- Close reaper
5.- Open Standalone
6.- Crash
7.- Logs:

[_2_Jamtaba64.json.txt](https://github.com/elieserdejesus/JamTaba/files/29431/_2_Jamtaba64.json.txt)
[_2_log.txt](https://github.com/elieserdejesus/JamTaba/files/29432/_2_log.txt)

**Comment by Ezeer** [comment] 2015-11-07 23:50
cool , thank you , i look at dem and i'll edit here .
go go go !
lol

**Comment by Ezeer** [comment] 2015-11-07 23:59
i have found one difference in the Json at channel level
look : 
"name": "your channel",
"name": "new channel",

i don't know yet if it is an issue

**Comment by jonjamcam** [comment] 2015-11-08 00:18
THis is what I found conparing both json files

[changes.txt](https://github.com/elieserdejesus/JamTaba/files/29436/changes.txt)

**Comment by jonjamcam** [comment] 2015-11-08 01:11
This I found is different between the json that works and the one that dowsn't

**********Doesn't work
"location": {
            "x": -0.0058565153740346432,
            "y": -0.0390625
        },
 **********
**********Does work
"location": {
            "x": 0,
            "y": 0
        },
**********

makes sense?

**Comment by jonjamcam** [comment] 2015-11-08 02:02
another try guys.... on the left..json with 2 channels working...on the right json that crashes after vst

![spot the difference](https://cloud.githubusercontent.com/assets/15310433/11018327/74af062a-85a3-11e5-8231-4d2c02318a93.jpg)

**Comment by Ezeer** [comment] 2015-11-08 02:12
ah ah ah , nice job !
I am working actually on an other bug , i'll look at that later , thanks !

**Comment by jonjamcam** [comment] 2015-11-08 02:33
I can't spot the difference on this one!

![spot2](https://cloud.githubusercontent.com/assets/15310433/11018438/dc914c90-85a7-11e5-905f-706d5e05bff8.jpg)

**Comment by Ezeer** [comment] 2015-11-08 02:41
use notepad++ , it's our coder's friend under windows : 
https://notepad-plus-plus.org/download/v6.8.6.html

The data will be better formatted to read !
That helps a lot .
^^

**Comment by jonjamcam** [comment] 2015-11-08 02:42
Found it!

![spot2_fixed](https://cloud.githubusercontent.com/assets/15310433/11018482/350a0b18-85a9-11e5-8941-f1da22402ae4.jpg)

**Comment by Ezeer** [comment] 2015-11-08 02:44
lol , " une aiguille dans une botte de foin " !
http://golem13.fr/sven-sachsalber-aiguille-foin/
![sven-sachsalber-performance](https://cloud.githubusercontent.com/assets/1283808/11018484/04ce275a-85cb-11e5-8588-ddd491ce1cc5.jpg)

**Comment by jonjamcam** [comment] 2015-11-08 02:46
lol! That value is change among many others.....just went 1 by one and voilá.....but the boss may know why this happens.......

**Comment by elieserdejesus** [comment] 2015-11-08 11:19
Ah, I can see the problem now, clear like water :)

You create 2 stereo channels in the VST plugin, and this works because inside a DAW you can use 4 mono inputs (2 stereo pairs). If you are using 4 mono inputs inside a DAW your fist channel in jamtaba is assigned like this:
```
firstInput: 0
channelsCount=2
```
FirstInput with a value 0 means "use the first input channel". If you change the "firstInput" to 1 you are using your second audio channel, etc.
So, when you create a second channel in Jamtaba Plugin this channel is using
```
firstInput: 2
channelsCount: 2
```
Your second jamtaba channel is a stereo pair (channelsCount = 2) and the first audio input channel in this Jamtaba channel is the third audio input channel (index value = 2). So your jamtaba channel is using the audio inputs 2 & 3, and your first Jamtaba channel is using inputs 0 & 1.

Everything works, and the world is a nice place to live, until you back to standalone :)

When open Standalone Jamtaba read the json and found the 2 jamtaba channels last used in VST plugin.
The first channel work because is using your audio input 0 & 1, and you have 2 input channels in your audio device.
After initialize the first Jamtaba channel the second channel is initialized too, because json has two channels (the second was created in the Plugin). Jamtaba is setting your second Jamtaba channel to use audio inputs 2 & 3, but youd audio device is not a 4 inputs audio device, right?
So you crash, because Jamtaba is trying use a non existent input channel in your audio device.

When you set the "firstInput" to -1 Jamtaba will use the first available input channel in your audio device, so this works too. The value -1 means "use the default audio input channel, user don't choose any inputs yet".

I really write a lot of checks in the code to avoid these kind of problems, but it's clear now this is a bug, and a cool one.

Probabily this is a quick fix because we have all details (thanks again Jon).

**Comment by Ezeer** [comment] 2015-11-08 11:28
The solution is to write a .json for the plugin version AND a json for the standalone .
lol

**Comment by elieserdejesus** [comment] 2015-11-08 11:36
I agree, 2 json solve the issue, but we loose some convenience for users. I like rename my channels in the PLugin and see these names in standalone too. If a change my metronome pan and level in the Plugin I expect see the same setup when back to standalone. 

In this case I think is best fix the bug and keep these little convenience for users.

**Comment by Ezeer** [comment] 2015-11-08 11:54
**"I agree, 2 json solve the issue, but we loose some convenience for users. "**
Dear Jamtaba team , i am an happy user of jamtaba , but something drive me crazy : 
![rambo](https://cloud.githubusercontent.com/assets/1283808/11020182/b8cf147a-8617-11e5-80ad-5840712a826c.jpg)

i WANT TO USE a different setup in the standalone and the plugin , and every time my setup is lost .
Any remedy to that , please ?
^^

**Comment by elieserdejesus** [comment] 2015-11-08 12:19
haha, this is true!
Maybe the best thing from user point of view is different setups.
@jonjamcam What you think about this, from an user perspective?

**Comment by jonjamcam** [comment] 2015-11-08 13:11
I think the best is to independent configuration files. The reason is that the vst is used -I would argue- for configuraions that can't be achieved in standalone or if there's a special function that only Cubase has that type of thing.

But maybe we should ask more users in the ninbot forum if they use vst or standalone and why. I think mostly Jamtaba is used as vst, but that's just my guess.

**Comment by elieserdejesus** [comment] 2015-11-08 13:30
I fix the bug.
Agree with the idea of 2 separated config files.
I'm closing this and opening a new issue to create 2 config files.

**Closed by elieserdejesus** 2015-11-08 13:30 UTC
Labels: bug
