### ISSUE TITLE
when using 2.1.2 others using 2.1.1 hear me with audio problems

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#956] opened 2017-10-25 02:44 UTC
using my compiled version of 2.1.2, creative and trashcanhead said they heard me with clicks and pops, so I installed 2.1.1 and seems problems dissapeared.

**Comment by elieserdejesus** [comment] 2017-10-25 12:23
@jonjamcam , I tested here xmiting audio + video:
1) JamTaba 2.1.2 xmiting to ReaNinjam
2) JamTaba 2.1.2 xmiting to JamTaba 2.1.1

 I noticed some clicks (very few) in the first tests. I was testing JamTaba v2.1.1 compiled in debug mode. I recompiled in release mode and no more clicks. The audio was clean.

**Can you remember if you are in the debug version when creative and trashcan reported the audio clicks?**  The debug mode is very slow in comparison with release, so the audio processing will run in very poor performance.

**Comment by jonjamcam** [comment] 2017-10-25 13:15
Yes. I was using a version compiled in debug mode. That must have been the cause. No worries then 😁.Closing...

**Comment by elieserdejesus** [comment] 2017-10-29 23:02
@jonjamcam , I received an email from HammerOn about this issue. I checked the server and Vadim was playing using v2.1.2. I entered in the server using v2.1.2 too and see the problem: **an audio click in every interva start**. I leave the server and checked the ninbot stream: same problem. 

So it's something in the audio transmission related with the interval begin. I will work in this problem and release an **emergency version** soon.

**Comment by elieserdejesus** [comment] 2017-10-30 16:54
fixed in 9a27ff26573f9ba6f9c2dcbfe17ebc38d76f74ff

![image](https://user-images.githubusercontent.com/1012741/32184063-3a1ca616-bd82-11e7-8951-8d50a189449b.png)

**Comment by elieserdejesus** [comment] 2018-12-25 22:18
Tom (from ninbot) reported a problem in audio in the v2.1.7.  

The last commit touching the audio code  is https://github.com/elieserdejesus/JamTaba/commit/a9e4249b93477248c2e6f01ceb4180479b8f9746.  @fab672000 and @jonjamcam , please help checking if we have a problem in the last version (maybe is just something in Tom machine).

Merry Christmas!! (even if you are Merry Cristmas guys 😄)

**Comment by fab672000** [comment] 2018-12-26 00:55
Got a quick build setup in Windows working again, rebuilt latest 64-bit version , which version are you using Eli 32 bits or 64 bits?

**Comment by elieserdejesus** [comment] 2018-12-26 10:14
> which version are you using Eli 32 bits or 64 bits?
@fab672000 , I'm using 64 bits, but I have Qt compiled in 32 and 64 bits to generate the 2 installers.

**Comment by elieserdejesus** [comment] 2018-12-26 11:17
@fab672000 and @jonjamcam , I tested here xmiting **a 220 Hz sine wave from JamTaba to ReaNinjam**. Recorded the received data in ReaNinjam and opened the clipsort.log file in Reaper. **There is no gap in xmited audio, so we don have the bug described in this issue**.

Maybe we have another audio bug, or maybe no bug.

I will close the issue until we have other clues.

![image](https://user-images.githubusercontent.com/1012741/50444313-fa888380-08ee-11e9-960a-f4abc2db05a0.png)

**Closed by elieserdejesus** 2018-12-26 11:17 UTC

**Comment by elieserdejesus** [comment] 2018-12-26 11:38
Tested again listening 3 ninjamers playing in a server and I can hear the bug. It's a audio gap in every interval begin.

@fab672000 , you are right about this:
```
SamplesBuffer::SamplesBuffer(unsigned int channels) :
    SamplesBuffer(channels, 4096) // <- try revert to 0?
```

**Comment by fab672000** [comment] 2018-12-26 12:51
Glad I could help, that's what made most sense to my static analysis even though I could not reproduce it, all the other audio code is running faster than before so I could not think of anything to change there.

It is surprising to me though that pre-allocating the buffers on the heap creates a problem. 
In future we should probably define our own allocators with continuous memory mapping so that we favor cache hits in our modern processors, and allocate them before entering the audio loop.

**Comment by elieserdejesus** [comment] 2018-12-26 13:01
> It is surprising to me though that pre-allocating the buffers on the heap creates a problem.

Me too, I think the std::vector size is wrongly used in some part of the audio code. At moment I will just release a hot fix.

**Comment by fab672000** [comment] 2018-12-26 13:15
Thanks! 2.1.8 looks good, in my version i added a comment there for future, I'll update it later.
