### ISSUE TITLE
Loading Presets collapses track in a strange way (standalone)

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#672] opened 2017-01-19 19:30 UTC
![image](https://cloud.githubusercontent.com/assets/15310433/22121887/75277ce8-de64-11e6-8ebc-d4020d1a3a96.png)

Can't test if this happens with the vst plugin too.

**Comment by elieserdejesus** [comment] 2017-01-19 21:19
I see the same problem in AU plugin. I was thinking this is a Mac + Qt problem, but now I'm seeing is a general problem.

**Comment by elieserdejesus** [comment] 2017-01-26 13:52
It's fixed in last commits, I can't reproduce the problem in last version.

**Closed by elieserdejesus** 2017-01-26 13:52 UTC

**Comment by jonjamcam** [comment] 2017-01-27 11:32
Same here. It's already fixed.
